database:
  driverClass: com.mysql.jdbc.Driver
  user: root
  password: password
  url: jdbc:mysql://127.0.0.1/exchange-rate
  properties:
    charSet: UTF-8
    hibernate.dialect: org.hibernate.dialect.MySQLInnoDBDialect
  maxWaitForConnection: 1s
  validationQuery: "/* MyApplication Health Check */ SELECT 1"
  minSize: 8
  maxSize: 32
  checkConnectionWhileIdle: false

exchangeRateFillerConfig:
  isEnabled: true
  concurrency: 1
  timeInterval: 15
  timeUnit: MINUTES
  - sourceCurrency: BITCOIN
    targetCurrency: USD
    isBackfillEnabled: true
    backfillFrom: 2019-01-01 #yyyy-MM-dd
    backfillTill: 2019-02-28 #yyyy-MM-dd

